=== agonjor/LMSGI_UD4/clientes_v2/clientes.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/clientes.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE clientes SYSTEM "clientes.dtd">

    <clientes>
    ...
    </clientes>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT clientes (sede)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT sede (direccion|empleado|fecha|descripcion|cliente)*>
<!ATTLIST sede
    codigo CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT direccion (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT empleado (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT fecha (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT descripcion (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT cliente (numero|vivienda)*>
<!ATTLIST cliente
    codigo CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT numero (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT vivienda (coste|resumen|plazo)*>
<!ATTLIST vivienda
    ID CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT coste (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT resumen (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT plazo (#PCDATA)>

=== agonjor/LMSGI_UD4/clientes_v2/clientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clientes SYSTEM "clientes.dtd">
<clientes>
    <sede codigo="A0000001">
        <direccion>C/Castilla, 1</direccion>
        <direccion>C/Castilla, 1</direccion>
        <empleado>José luis Comesaña</empleado>
        <fecha>12-01-2012</fecha>
        <descripcion>Urgente</descripcion>
        <cliente codigo="AAA-111">
            <numero>12</numero>
            <vivienda ID="001">
                <coste>100</coste>
                <resumen>Producto muy frágil</resumen>
                <plazo>10</plazo>
            </vivienda>
             <vivienda ID="002">
                <coste>130</coste>
                <resumen>Producto nada frágil</resumen>
                <plazo>17</plazo>
            </vivienda>
        </cliente>
        <cliente codigo="AAA-112">
            <numero>10</numero>
            <vivienda ID="001">
                <coste>100</coste>
                <resumen>Producto muy frágil</resumen>
                <plazo>10</plazo>
            </vivienda>
             <vivienda ID="002">
                <coste>130</coste>
                <resumen>Producto nada frágil</resumen>
                <plazo>17</plazo>
            </vivienda>
        </cliente>
    </sede>
    <sede codigo="B0000002">
        <direccion>Avda. Gran Vía s/n</direccion>
        <empleado>Antonio Resines</empleado>
        <fecha>10-02-2012</fecha>
        <cliente codigo="ABC-001">
            <numero>5</numero>
            <vivienda ID="001">
                <coste>100</coste>
                <resumen>Producto muy frágil</resumen>
                <plazo>10</plazo>
            </vivienda>
             <vivienda ID="002">
                <coste>130</coste>
                <resumen>Producto nada frágil</resumen>
                <plazo>17</plazo>
            </vivienda>
        </cliente>
    </sede>
</clientes>
